// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrometheonSuite.Identity.Infrastructure.Data;

#nullable disable

namespace PrometheonSuite.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrometheonSuite.Identity.Core.Entities.TokenAggregate.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.ApplicazioneAggregate.Applicazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Applicazione", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.AziendaAggregate.Azienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Azienda", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.AziendaApplicazioneAggregate.AziendaApplicazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicazioneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AziendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicazioneId");

                    b.HasIndex("AziendaId", "ApplicazioneId")
                        .IsUnique();

                    b.ToTable("AziendaApplicazione", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.FiguraAggregate.Figura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicazioneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicazioneId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Figura", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.FiguraAggregate.FiguraRuolo", b =>
                {
                    b.Property<Guid>("FiguraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RuoloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FiguraId", "RuoloId");

                    b.ToTable("FiguraRuolos", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.RuoloAggregate.Ruolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicazioneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicazioneId", "Code")
                        .IsUnique();

                    b.ToTable("Ruolo", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.UtenteAggregate.Utente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Utenti", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.UtenteApplicazioneAziendaAggregate.UtenteApplicazioneAzienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicazioneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AziendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultLocale")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AziendaId", "ApplicazioneId")
                        .IsUnique();

                    b.ToTable("UtenteApplicazioneAzienda", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.UtenteApplicazioneAziendaAggregate.UtenteApplicazioneAziendaFigura", b =>
                {
                    b.Property<Guid>("UtenteApplicazioneAziendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FiguraId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UtenteApplicazioneAziendaId", "FiguraId");

                    b.ToTable("UtenteApplicazioneAziendaFiguras", (string)null);
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.AziendaApplicazioneAggregate.AziendaApplicazione", b =>
                {
                    b.HasOne("PrometheonSuite.Identity.Entities.ApplicazioneAggregate.Applicazione", null)
                        .WithMany()
                        .HasForeignKey("ApplicazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrometheonSuite.Identity.Entities.AziendaAggregate.Azienda", null)
                        .WithMany()
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.FiguraAggregate.Figura", b =>
                {
                    b.HasOne("PrometheonSuite.Identity.Entities.ApplicazioneAggregate.Applicazione", null)
                        .WithMany()
                        .HasForeignKey("ApplicazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.FiguraAggregate.FiguraRuolo", b =>
                {
                    b.HasOne("PrometheonSuite.Identity.Entities.FiguraAggregate.Figura", null)
                        .WithMany("FiguraRuolos")
                        .HasForeignKey("FiguraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.RuoloAggregate.Ruolo", b =>
                {
                    b.HasOne("PrometheonSuite.Identity.Entities.ApplicazioneAggregate.Applicazione", null)
                        .WithMany()
                        .HasForeignKey("ApplicazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.UtenteApplicazioneAziendaAggregate.UtenteApplicazioneAziendaFigura", b =>
                {
                    b.HasOne("PrometheonSuite.Identity.Entities.UtenteApplicazioneAziendaAggregate.UtenteApplicazioneAzienda", null)
                        .WithMany("UtenteApplicazioneAziendaFiguras")
                        .HasForeignKey("UtenteApplicazioneAziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.FiguraAggregate.Figura", b =>
                {
                    b.Navigation("FiguraRuolos");
                });

            modelBuilder.Entity("PrometheonSuite.Identity.Entities.UtenteApplicazioneAziendaAggregate.UtenteApplicazioneAzienda", b =>
                {
                    b.Navigation("UtenteApplicazioneAziendaFiguras");
                });
#pragma warning restore 612, 618
        }
    }
}
